FROM golang:1.22 AS build

# Set destination for COPY
WORKDIR /app
# Download Go modules
COPY go.mod go.sum ./
RUN go mod download
# Copy the source code.
COPY ./ ./
# Build
RUN CGO_ENABLED=0 GOOS=linux go build -o /main

FROM alpine:3.14
# Copy the binary
COPY --from=build /main .
# Expose
EXPOSE 8000
# Run
CMD ["/main"]