name: alati2024

on:
  push:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.22

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build -t mtucakov/alati2024:latest .

      - name: Push Docker image
        run: docker push mtucakov/alati2024:latest

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.12.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest selenium chromedriver-autoinstaller

      - name: Run Docker Compose services
        run: docker-compose up -d

      - name: Wait for services to be ready
        run: |
          while ! curl -sSf http://localhost:8080 > /dev/null; do
            echo "Waiting for application to be ready..."
            sleep 10
          done

      - name: Run tests
        run: pytest alati_test.py

      - name: Tear down Docker Compose services
        if: always()
        run: docker-compose down
